version: '3.8'

services:
  rogueletters:
    build: .
    container_name: rogueletters-dev
    ports:
      - "8086:80"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
      - ./script.js:/usr/local/apache2/htdocs/script.js
      - ./styles.css:/usr/local/apache2/htdocs/styles.css
      - ./cgi-bin:/usr/local/apache2/cgi-bin
      - ./data:/usr/local/apache2/data
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CGITB_ENABLE=1
